// Build "script" that loads, decodes and converts assets into a ./build/assets.h file

#include <stdio.h>
#include <assert.h>
#include <math.h>

#define STB_TRUETYPE_IMPLEMENTATION
#include "./stb_truetype.h"

#define CODEPOINT_START 0x20
#define CODEPOINT_STOP 0x3000
#define CODEPOINT_COUNT (CODEPOINT_STOP - CODEPOINT_START + 1)

#define BITMAP_WIDTH (8 * 128)
#define BITMAP_HEIGHT (8 * 92)
#define BITMAP_LEN (BITMAP_WIDTH * BITMAP_HEIGHT)

void generate_font(FILE *file, const char *name, const char *path, int base_size) {
	unsigned char ttf_buffer[1 << 20];
	unsigned char bitmap[BITMAP_LEN];

	stbtt_bakedchar bboxes[CODEPOINT_COUNT];

	FILE *ttf_file = fopen(path, "rb");
	assert(ttf_file);

	// Raterize font
	fread(ttf_buffer, 1, 1 << 20, ttf_file);
	stbtt_BakeFontBitmap(
		ttf_buffer,
		0,
		base_size,
		bitmap,
		BITMAP_WIDTH,
		BITMAP_HEIGHT,
		CODEPOINT_START,
		CODEPOINT_STOP,
		bboxes
	);
	fclose(ttf_file);

#if 0
	// Generate PBM image
	FILE *img = fopen(name, "wb");
	fprintf(img, "P4\n%d %d\n", BITMAP_WIDTH, BITMAP_HEIGHT);
	for (int i = 0; i < BITMAP_LEN; i += 8) {
		unsigned char byte = 0;
		byte |= bitmap[i + 0] ? 1 << 7 : 0;
		byte |= bitmap[i + 1] ? 1 << 6 : 0;
		byte |= bitmap[i + 2] ? 1 << 5 : 0;
		byte |= bitmap[i + 3] ? 1 << 4 : 0;
		byte |= bitmap[i + 4] ? 1 << 3 : 0;
		byte |= bitmap[i + 5] ? 1 << 2 : 0;
		byte |= bitmap[i + 6] ? 1 << 1 : 0;
		byte |= bitmap[i + 7] ? 1 << 0 : 0;
		fputc(byte, img);
	}
	fclose(img);
#else
	// Write font data into the output file
	fprintf(file, "#define %s_BASE_SIZE %d\n", name, (int)base_size);
	fprintf(file, "#define %s_GLYPH_COUNT %d\n", name, (int)CODEPOINT_COUNT);
	fprintf(file, "#define %s_GLYPH_PADDING 0\n", name);
	fprintf(file, "#define %s_IMAGE_WIDTH %d\n", name, BITMAP_WIDTH);
	fprintf(file, "#define %s_IMAGE_HEIGHT %d\n", name, BITMAP_HEIGHT);
	fprintf(file, "#define %s_PIXEL_FORMAT PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA\n", name);

	fprintf(file, "extern Rectangle %s_RECTS[];\n", name);
	fprintf(file, "extern GlyphInfo %s_GLYPHS[];\n", name);
	fprintf(file, "extern unsigned char %s_IMAGE_DATA[];\n", name);

	fprintf(file, "#ifdef ASSETS_IMPLEMENTATION\n");
	fprintf(file, "Rectangle %s_RECTS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		unsigned short w = bboxes[i].x1 - bboxes[i].x0;
		unsigned short h = bboxes[i].y1 - bboxes[i].y0;
		fprintf(file, "{%d,%d,%d,%d},\n", bboxes[i].x0, bboxes[i].y0, w, h);
	}
	fprintf(file, "};\n\n");

	fprintf(file, "GlyphInfo %s_GLYPHS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		fprintf(
			file,
			"{%d,%d,%d,%d,{0}},\n",
			CODEPOINT_START + i,
			(int)bboxes[i].xoff,
			(int)bboxes[i].yoff + base_size,
			(int)bboxes[i].xadvance
		);
	}
	fprintf(file, "};\n\n");

	fprintf(file, "unsigned char %s_IMAGE_DATA[] = {\n", name);

	for (int i = 0; i < BITMAP_LEN; i++) {
		fprintf(file, "%d,%d,", 255, bitmap[i]);
		if (i % 64 == 0) fputc('\n', file);
	}

	fprintf(file, "\n};\n\n");

	fprintf(file, "#endif\n");
#endif
}

int main() {
	FILE *output_file = fopen("./build/assets.h", "w");
	fprintf(
		output_file,
		"// Generated by 'build_src/gen_assets.c'\n"
		"#ifndef ASSETS_H\n"
		"#define ASSETS_H\n"
		"#include <raylib.h>\n"
		"\n"
	);

	generate_font(output_file, "code9x7", "assets/fonts/code9x7.ttf", 16);
	generate_font(output_file, "comicoro", "assets/fonts/comicoro.ttf", 15);

	fprintf(output_file, "#endif\n");
	fclose(output_file);

	return 0;
}
