// Build "script" that loads, decodes and converts assets into a ./build/assets.h file

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <raylib.h>
#include <math.h>

#define CODEPOINT_START 0x20
#define CODEPOINT_STOP 0x3000
#define CODEPOINT_COUNT (CODEPOINT_STOP - CODEPOINT_START + 1)

int format_comps(PixelFormat format) {
	if (format == PIXELFORMAT_UNCOMPRESSED_GRAYSCALE) return 1;
	if (format == PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA) return 2;
	if (format == PIXELFORMAT_UNCOMPRESSED_R8G8B8) return 3;
	if (format == PIXELFORMAT_UNCOMPRESSED_R8G8B8A8) return 4;

	fprintf(stderr, "ERROR: Unhandled image format (%d)\n", format);
	exit(1);
}

void generate_font(FILE *c_file, FILE *h_file, const char *name, const char *path, int base_size) {
	int codepoints[CODEPOINT_COUNT];
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		codepoints[i] = i + CODEPOINT_START;
	}

	Font font = LoadFontEx(path, base_size, codepoints, CODEPOINT_COUNT);
	Image image = LoadImageFromTexture(font.texture);

	// Header file

	// Write font data into the output file
	fprintf(h_file, "#define %s_BASE_SIZE %d\n", name, (int)base_size);
	fprintf(h_file, "#define %s_GLYPH_COUNT %d\n", name, (int)CODEPOINT_COUNT);
	fprintf(h_file, "#define %s_GLYPH_PADDING 0\n", name);
	fprintf(h_file, "#define %s_IMAGE_WIDTH %d\n", name, image.width);
	fprintf(h_file, "#define %s_IMAGE_HEIGHT %d\n", name, image.height);
	fprintf(h_file, "#define %s_PIXEL_FORMAT PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA\n", name);

	fprintf(h_file, "extern Rectangle %s_RECTS[];\n", name);
	fprintf(h_file, "extern GlyphInfo %s_GLYPHS[];\n", name);
	fprintf(h_file, "extern unsigned char %s_IMAGE_DATA[];\n", name);

	// Actual data in C file

	// Generate rectangles
	fprintf(c_file, "Rectangle %s_RECTS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		fprintf(
			c_file,
			"{%f,%f,%f,%f},\n",
			font.recs[i].x,
			font.recs[i].y,
			font.recs[i].width,
			font.recs[i].height
		);
	}
	fprintf(c_file, "};\n\n");

	// Generate glyph info
	fprintf(c_file, "GlyphInfo %s_GLYPHS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		fprintf(
			c_file,
			"{%d,%d,%d,%d,{0}},\n",
			font.glyphs[i].value,
			font.glyphs[i].offsetX,
			font.glyphs[i].offsetY,
			font.glyphs[i].advanceX
		);
	}
	fprintf(c_file, "};\n\n");

	// Generate image data
	int comps = format_comps(image.format);
	fprintf(c_file, "unsigned char %s_IMAGE_DATA[] = {\n", name);
	for (int i = 0; i < image.width * image.height * comps; i += comps) {
		fprintf(c_file, "%d,%d,", 255, ((unsigned char*)image.data)[i + 1]);
		if (i % 128 == 0) fputc('\n', c_file);
	}
	fprintf(c_file, "\n};\n\n");
}

void generate_image(FILE* c_file, FILE *h_file, const char *name, const char *path) {
	Image image = LoadImage(path);

	// Header file

	fprintf(h_file, "#define %s_WIDTH %d\n", name, image.width);
	fprintf(h_file, "#define %s_HEIGHT %d\n", name, image.height);

	int comps = format_comps(image.format);
	fprintf(h_file, "#define %s_PIXEL_FORMAT ", name);
	if (comps == 1) {
		fprintf(h_file, "PIXELFORMAT_UNCOMPRESSED_GRAYSCALE\n");
	} else if (comps == 2) {
		fprintf(h_file, "PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA\n");
	} else if (comps == 3) {
		fprintf(h_file, "PIXELFORMAT_UNCOMPRESSED_R8G8B8\n");
	} else if (comps == 4) {
		fprintf(h_file, "PIXELFORMAT_UNCOMPRESSED_R8G8B8A8\n");
	}

	fprintf(h_file, "extern unsigned char %s_DATA[];\n", name);

	// Actual data in C file

	// Generate image data
	fprintf(c_file, "unsigned char %s_DATA[] = {\n", name);
	for (int i = 0; i < image.width * image.height * comps; i += comps) {
		for (int j = 0; j < comps; j++) {
			fprintf(c_file, "%d,", ((unsigned char*)image.data)[i + j]);
		}
		if (i % 64 == 0) fputc('\n', c_file);
	}
	fprintf(c_file, "\n};\n\n");
}

int main() {
	FILE *output_c_file = fopen("./build/assets.c", "w");
	FILE *output_h_file = fopen("./build/assets.h", "w");
	fprintf(
		output_h_file,
		"// Generated by 'build_src/gen_assets.c'\n"
		"#ifndef GENERATED_ASSETS_H\n"
		"#define GENERATED_ASSETS_H\n"
		"#include <raylib.h>\n"
		"\n"
	);
	fprintf(
		output_c_file,
		"// Generated by 'build_src/gen_assets.c'\n"
		"#include \"./assets.h\"\n"
		"\n"
	);

	SetTraceLogLevel(LOG_WARNING);
	InitWindow(0, 0, "");

	generate_font(output_c_file, output_h_file, "code9x7", "assets/fonts/code9x7.ttf", 16);
	generate_font(output_c_file, output_h_file, "comicoro", "assets/fonts/comicoro.ttf", 15);

	generate_image(output_c_file, output_h_file, "empty_artwork", "assets/images/empty-artwork.png");
	generate_image(output_c_file, output_h_file, "icons", "assets/images/icons.png");
	generate_image(output_c_file, output_h_file, "boxes", "assets/images/boxes.png");
	generate_image(output_c_file, output_h_file, "lines", "assets/images/lines.png");

	CloseWindow();

	fprintf(output_h_file, "#endif\n");

	fclose(output_h_file);
	fclose(output_c_file);

	return 0;
}
