// Build "script" that loads, decodes and converts assets into a ./build/assets.h file

#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <raylib.h>
#include <math.h>

#define CODEPOINT_START 0x20
#define CODEPOINT_STOP 0x3000
#define CODEPOINT_COUNT (CODEPOINT_STOP - CODEPOINT_START + 1)

int format_comps(PixelFormat format) {
	if (format == PIXELFORMAT_UNCOMPRESSED_GRAYSCALE) return 1;
	if (format == PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA) return 2;
	if (format == PIXELFORMAT_UNCOMPRESSED_R8G8B8) return 3;
	if (format == PIXELFORMAT_UNCOMPRESSED_R8G8B8A8) return 4;

	fprintf(stderr, "ERROR: Unhandled image format (%d)\n", format);
	exit(1);
}

void generate_font(FILE *file, const char *name, const char *path, int base_size) {
	int codepoints[CODEPOINT_COUNT];
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		codepoints[i] = i + CODEPOINT_START;
	}

	Font font = LoadFontEx(path, base_size, codepoints, CODEPOINT_COUNT);
	Image image = LoadImageFromTexture(font.texture);

	// Write font data into the output file
	fprintf(file, "#define %s_BASE_SIZE %d\n", name, (int)base_size);
	fprintf(file, "#define %s_GLYPH_COUNT %d\n", name, (int)CODEPOINT_COUNT);
	fprintf(file, "#define %s_GLYPH_PADDING 0\n", name);
	fprintf(file, "#define %s_IMAGE_WIDTH %d\n", name, image.width);
	fprintf(file, "#define %s_IMAGE_HEIGHT %d\n", name, image.height);
	fprintf(file, "#define %s_PIXEL_FORMAT PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA\n", name);

	fprintf(file, "extern Rectangle %s_RECTS[];\n", name);
	fprintf(file, "extern GlyphInfo %s_GLYPHS[];\n", name);
	fprintf(file, "extern unsigned char %s_IMAGE_DATA[];\n", name);

	fprintf(file, "#ifdef ASSETS_IMPLEMENTATION\n");

	// Generate rectangles
	fprintf(file, "Rectangle %s_RECTS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		fprintf(
			file,
			"{%f,%f,%f,%f},\n",
			font.recs[i].x,
			font.recs[i].y,
			font.recs[i].width,
			font.recs[i].height
		);
	}
	fprintf(file, "};\n\n");

	// Generate glyph info
	fprintf(file, "GlyphInfo %s_GLYPHS[] = {\n", name);
	for (int i = 0; i < CODEPOINT_COUNT; i++) {
		fprintf(
			file,
			"{%d,%d,%d,%d,{0}},\n",
			font.glyphs[i].value,
			font.glyphs[i].offsetX,
			font.glyphs[i].offsetY,
			font.glyphs[i].advanceX
		);
	}
	fprintf(file, "};\n\n");

	// Generate image data
	int comps = format_comps(image.format);
	fprintf(file, "unsigned char %s_IMAGE_DATA[] = {\n", name);
	for (int i = 0; i < image.width * image.height * comps; i += comps) {
		fprintf(file, "%d,%d,", 255, ((unsigned char*)image.data)[i + 1]);
		if (i % 128 == 0) fputc('\n', file);
	}
	fprintf(file, "\n};\n\n");

	fprintf(file, "#endif\n");
}

void generate_image(FILE *file, const char *name, const char *path) {
	Image image = LoadImage(path);

	fprintf(file, "#define %s_WIDTH %d\n", name, image.width);
	fprintf(file, "#define %s_HEIGHT %d\n", name, image.height);

	int comps = format_comps(image.format);
	fprintf(file, "#define %s_PIXEL_FORMAT ", name);
	if (comps == 1) {
		fprintf(file, "PIXELFORMAT_UNCOMPRESSED_GRAYSCALE\n");
	} else if (comps == 2) {
		fprintf(file, "PIXELFORMAT_UNCOMPRESSED_GRAY_ALPHA\n");
	} else if (comps == 3) {
		fprintf(file, "PIXELFORMAT_UNCOMPRESSED_R8G8B8\n");
	} else if (comps == 4) {
		fprintf(file, "PIXELFORMAT_UNCOMPRESSED_R8G8B8A8\n");
	}

	fprintf(file, "extern unsigned char %s_DATA[];\n", name);

	fprintf(file, "#ifdef ASSETS_IMPLEMENTATION\n");

	// Generate image data
	fprintf(file, "unsigned char %s_DATA[] = {\n", name);
	for (int i = 0; i < image.width * image.height * comps; i += comps) {
		for (int j = 0; j < comps; j++) {
			fprintf(file, "%d,", ((unsigned char*)image.data)[i + j]);
		}
		if (i % 64 == 0) fputc('\n', file);
	}
	fprintf(file, "\n};\n\n");

	fprintf(file, "#endif\n");
}

int main() {
	FILE *output_file = fopen("./build/assets.h", "w");
	fprintf(
		output_file,
		"// Generated by 'build_src/gen_assets.c'\n"
		"#ifndef ASSETS_H\n"
		"#define ASSETS_H\n"
		"#include <raylib.h>\n"
		"\n"
	);

	SetTraceLogLevel(LOG_WARNING);
	InitWindow(0, 0, "");

	generate_font(output_file, "code9x7", "assets/fonts/code9x7.ttf", 16);
	generate_font(output_file, "comicoro", "assets/fonts/comicoro.ttf", 15);

	generate_image(output_file, "empty_artwork", "assets/images/empty-artwork.png");
	generate_image(output_file, "icons", "assets/images/icons.png");
	generate_image(output_file, "boxes", "assets/images/boxes.png");

	CloseWindow();

	fprintf(output_file, "#endif\n");
	fclose(output_file);

	return 0;
}
