// Generated by "prebuild/prebuild.odin".

package mupwit

IMAGE_SCREEN_ART_SIZE :: [2]i32{280, 170}
IMAGE_ICONS_SIZE :: [2]i32{144, 16}
IMAGE_CLIPPY_OUTLINE_SIZE :: [2]i32{53, 60}
IMAGE_CLIPPY_SIZE :: [2]i32{53, 60}
