#ifndef THEME_H
#define THEME_H

#include <raylib.h>

#define THEME_WINDOW_WIDTH 360
#define THEME_WINDOW_HEIGHT 540

#define THEME_NORMAL_FONT_SIZE 16
#define THEME_TITLE_FONT_SIZE 15
#define THEME_NORMAL_TEXT_SIZE THEME_NORMAL_FONT_SIZE
#define THEME_TITLE_TEXT_SIZE (THEME_TITLE_FONT_SIZE * 2)

#define THEME_WHITE (GetColor(0xdbdce5ff))
#define THEME_BLACK (GetColor(0x111111ff))
#define THEME_GRAY (ColorAlpha(THEME_BLACK, 0.7))

#define THEME_BACKGROUND THEME_WHITE
#define THEME_TEXT THEME_BLACK
#define THEME_SUBTLE_TEXT THEME_GRAY

#endif
